version: 1
disable_existing_loggers: False

formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  json:
    (): structlog.stdlib.ProcessorFormatter
    processor: structlog.processors.JSONRenderer()

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: json
    filename: logs/terraform_generator.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: json
    filename: logs/error.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

loggers:
  flask:
    level: INFO
    handlers: [console, file]
    propagate: False
  
  flask.app:
    level: INFO
    handlers: [console, file]
    propagate: False

  app:
    level: DEBUG
    handlers: [console, file, error_file]
    propagate: False

root:
  level: INFO
  handlers: [console, file, error_file]
  propagate: False
